version: '3'

services:

# Anaconda environment
  jpynb:
    build: 
      context: .
      dockerfile: Dockerfile
    image: "${IMAGE_TO_RUN:-jpynb}"
    
    ports:
      - "8888"

    volumes:
      - "${MY_WORKAREA:-/tmp}:/opt/project/meda"

    # command to start jupyter notebook server
    command: >
           /opt/conda/bin/jupyter notebook --notebook-dir=/opt/project
              --ip=0.0.0.0 
              --port=8888 
              --no-browser 
              --NotebookApp.token=''
              --NotebookApp.terminado_settings="{'shell_command': ['/bin/bash']}"

    # -i docker run cli option
    stdin_open: true

    # -t docker run cli option    
    tty: true
