version: '3'

services:

# Anaconda environment
  lightgbm:
    build: 
      context: .
      dockerfile: Dockerfile
    image: lightgbm
    
    ports:
      - "8888"

    volumes:
      - "${MY_WORKAREA:-/tmp}:/my_workarea"

    # command to start jupyter notebook server
    command: >
           /opt/conda/bin/jupyter notebook --notebook-dir=/my_workarea 
              --ip=0.0.0.0 
              --port=8888 
              --no-browser 
              --NotebookApp.token=''

    # -i docker run cli option
    stdin_open: true

    # -t docker run cli option    
    tty: true
