version: '3'

services:

# Anaconda environment
  tfgpu:
    build: 
      context: .
      dockerfile: Dockerfile_tf
    image: tfgpu
    
    ports:
      - "8888"
      - "6006"

    volumes:
      - "${MY_WORKAREA:-/tmp}:/my_workarea"

    # command to start jupyter notebook server
    command: >
           /run_jupyter.sh  --notebook-dir=/my_workarea 
              --ip=0.0.0.0
              --port=8888 
              --no-browser 
              --NotebookApp.token=''

    # -i docker run cli option
    stdin_open: true

    # -t docker run cli option    
    tty: true
