# Base image compatitble with Tensorflow
FROM nvidia/cuda:9.0-cudnn7-devel-centos7

# add Aanconda version supported for Tensorflow



# install TensorFlow gpu version
#RUN pip install --ignore-installed \
#     --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.11.0-cp36-cp36m-linux_x86_64.whl


# specify run-time user
#RUN useradd ds_user && mkdir -p /home/ds_user && chown ds_user:staff /home/ds_user


# set user
#USER ds_user

