# Get specific version of Anaconda with the right version for Tensorflow
FROM continuumio/anaconda3:4.3.1

# install CUDA and cuDNN
ENV NCCL_VERSION 2.3.5

RUN apt-get update && apt-get install -y --no-install-recommends \
        cuda-libraries-$CUDA_PKG_VERSION \
        cuda-cublas-9-0=9.0.176.4-1 \
        libnccl2=$NCCL_VERSION-2+cuda9.0 && \
    apt-mark hold libnccl2 && \
    rm -rf /var/lib/apt/lists/*



# install TensorFlow gpu version
RUN pip install --ignore-installed \
     --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.11.0-cp36-cp36m-linux_x86_64.whl


# specify run-time user
RUN useradd ds_user && mkdir -p /home/ds_user && chown ds_user:staff /home/ds_user


# set user
USER ds_user

