version: '3'


services:

  rstudio:
    build:
      context: .
      dockerfile: Dockerfile_rstudio

    image: rstudio

    ports:
      - "8787"

    environment:
      - PASSWORD=rstudio_pw

    volumes:
      - "${MY_WORKAREA:-/tmp}:/my_workarea"
      
    # -i docker run cli option
    stdin_open: true

    # -t docker run cli option    
    tty: true

   
