version: '3'


services:

# Anaconda environment
  pyspnb:
    build: 
      context: .
      dockerfile: Dockerfile_pyspnb

    image: pyspnb
    
    ports:
      - "8888"
      - "4040"

    environment:
      - PYSPARK_DRIVER_PYTHON_OPTS=${PYSPARK_DRIVER_PYTHON_OPTS}

    volumes:
      - "${MY_WORKAREA:-/tmp}:/my_workarea"

    # command to start jupyter notebook server
    command: pyspark --driver-memory 8g --master local[*] 

    # -i docker run cli option
    stdin_open: true

    # -t docker run cli option    
    tty: true
