version: '3'


services:

# Anaconda environment
  pyspnb:
    #image: continuumio/anaconda3
    build: 
      context: .
      dockerfile: Dockerfile_pyspnb

    image: pyspnb
    
    ports:
      - "8888"
      - "4040"

    volumes:
      - "${MY_NOTEBOOKS:-/tmp}:/notebooks"

    # command to start jupyter notebook server
    # disable NotebookApp.token not recommended
    command:  pyspark --driver-memory 8g --master local[*] 

    # -i docker run cli option
    stdin_open: true

    # -t docker run cli option    
    tty: true
