version: '3'


services:

# Anaconda environment
  jpynb:
    #image: continuumio/anaconda3
    build: 
      context: .
      dockerfile: Dockerfile_jpynb
    
    ports:
      - "8888"

    volumes:
      - "/Users/jim/Desktop/notebook_sandbox:/notebooks"

    # command to start jupyter notebook server
    # disable NotebookApp.token not recommended
    command: >
           /opt/conda/bin/jupyter notebook --notebook-dir=/notebooks 
              --ip='*' 
              --port=8888 
              --no-browser 
              --NotebookApp.token=''

    # -i docker run cli option
    stdin_open: true

    # -t docker run cli option    
    tty: true


  rstudio:
    #image: rocker/rstudio:latest
    build: 
      context: .
      dockerfile: Dockerfile_rstudio

    ports:
      - "8787"

    env_file: rstudio.env

    volumes:
      - "/Users/jim/Desktop/notebook_sandbox:/notebooks"
      
    # -i docker run cli option
    stdin_open: true

    # -t docker run cli option    
    tty: true



   