#!/bin/bash

# launch chrome with the host port assigned to the exposed port
/usr/bin/open -a "/Applications/Google Chrome.app" \
"http://127.0.0.1:"\
`docker container inspect ds_container_rstudio_1 | jq -r '.[0].NetworkSettings.Ports."8787/tcp"[0].HostPort'`
